'use client';
import { useState } from 'react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, AreaChart, Area } from 'recharts';
import { API, postJSON, simulate } from '../services/api';
import type { Chunk, RouteDecision, Trace } from '../types/api';

export default function Page(){
  const [message,setMessage]=useState('Explain how vector cache improves RAG latency in distributed inference.');
  const [answer,setAnswer]=useState(''); const [chunks,setChunks]=useState<Chunk[]>([]); const [route,setRoute]=useState<RouteDecision|null>(null); const [trace,setTrace]=useState<Trace[]>([]); const [lat,setLat]=useState(0); const [tps,setTps]=useState(0);
  const metrics = Array.from({length:18},(_,i)=>({t:i,p95:120+Math.sin(i/2)*35+rnd(20),rps:30+rnd(10),cache:.45+Math.sin(i/3)*.18,tokens:80+rnd(50)}));
  async function chat(){ const started=performance.now(); setAnswer(''); setTrace([{stage:'client',status:'sent'}]); const res=await postJSON<any>('/chat',{message,use_rag:true,top_k:4}); setAnswer(res.answer); setChunks(res.retrieved_chunks); setRoute(res.route); setTrace(res.trace); setLat(res.latency_ms); setTps(Math.round(res.answer.split(' ').length/((performance.now()-started)/1000))); }
  function stream(){ setAnswer(''); setTrace([{stage:'sse',status:'connecting'}]); const started=performance.now(); let tokens=0; const es=new EventSource(`${API}/stream?message=${encodeURIComponent(message)}&use_rag=true`); es.addEventListener('retrieval',(e)=>setChunks(JSON.parse((e as MessageEvent).data))); es.addEventListener('route',(e)=>setRoute(JSON.parse((e as MessageEvent).data))); es.addEventListener('token',(e)=>{tokens++; setAnswer(a=>a+JSON.parse((e as MessageEvent).data).token); setTps(Math.round(tokens/((performance.now()-started)/1000)));}); es.addEventListener('fallback',(e)=>setTrace(t=>[...t,{stage:'fallback',status:'activated',detail:JSON.parse((e as MessageEvent).data)}])); es.addEventListener('done',(e)=>{setLat(JSON.parse((e as MessageEvent).data).duration_ms); es.close();}); }
  async function upload(file:File){ const fd=new FormData(); fd.append('file',file); await fetch(`${API}/upload`,{method:'POST',body:fd}); setTrace(t=>[...t,{stage:'upload',status:'indexed',detail:{file:file.name}}]); }
  return <main className="min-h-screen p-6"><header className="mb-6"><h1 className="text-3xl font-semibold text-cyan-100">Distributed LLM Inference + RAG Platform</h1><p className="text-slate-400">Inference routing, streaming, vector retrieval, cache degradation, and observability dashboard.</p></header>
    <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
      <div className="card"><div className="mb-3 flex gap-2"><input className="input flex-1" value={message} onChange={e=>setMessage(e.target.value)}/><button className="btn" onClick={chat}>Chat</button><button className="btn" onClick={stream}>Stream SSE</button></div><input type="file" className="mb-3 text-sm" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><div className="min-h-64 whitespace-pre-wrap rounded-lg bg-black/30 p-4 text-sm leading-6">{answer||'Response tokens will appear here...'}</div><div className="mt-3 flex gap-4 text-sm text-slate-300"><span>Latency: {Math.round(lat)} ms</span><span>Token/sec: {tps}</span><span>Model: {route?.model ?? '-'}</span></div></div>
      <div className="card"><h2 className="mb-2 font-semibold">Model Router Visualization</h2><div className="text-sm text-slate-300">Model: <b className="text-cyan-200">{route?.model}</b> · Confidence {route?.confidence} · Complexity {route?.complexity}</div><ul className="mt-2 list-disc pl-5 text-sm text-slate-400">{route?.reasons.map(r=><li key={r}>{r}</li>)}</ul><h2 className="mb-2 mt-5 font-semibold">Failure Simulation</h2><div className="flex flex-wrap gap-2">{['model_crash','redis_failure','timeout','clear'].map(f=><button className="btn" key={f} onClick={()=>simulate(f)}>{f}</button>)}</div></div>
      <div className="card"><h2 className="mb-3 font-semibold">Retrieval Visualization</h2><div className="space-y-3">{chunks.map(c=><div key={c.chunk_id} className="rounded-lg border border-slate-800 p-3"><div className="text-xs text-cyan-300">{c.source} · score {c.score.toFixed(3)}</div><p className="line-clamp-3 text-sm text-slate-300">{c.text}</p></div>)}</div></div>
      <div className="card"><h2 className="mb-3 font-semibold">Request Trace Panel</h2><ol className="space-y-2 text-sm">{trace.map((t,i)=><li key={i} className="rounded border border-slate-800 p-2"><span className="text-cyan-300">{t.stage}</span> — {t.status}</li>)}</ol></div>
      <div className="card xl:col-span-2"><h2 className="mb-3 font-semibold">Metrics Dashboard</h2><div className="grid h-64 grid-cols-1 gap-4 md:grid-cols-2"><ResponsiveContainer><LineChart data={metrics}><XAxis dataKey="t"/><YAxis/><Tooltip/><Line dataKey="p95" stroke="#22d3ee"/><Line dataKey="rps" stroke="#a78bfa"/></LineChart></ResponsiveContainer><ResponsiveContainer><AreaChart data={metrics}><XAxis dataKey="t"/><YAxis/><Tooltip/><Area dataKey="tokens" stroke="#34d399" fill="#064e3b"/><Area dataKey="cache" stroke="#fbbf24" fill="#713f12"/></AreaChart></ResponsiveContainer></div></div>
    </section></main> }
function rnd(n:number){ return Math.round(Math.random()*n); }
